### PR TITLE
Adding say network service in oracles folder

### PR DESCRIPTION
**Pull request by saynetwork**
Greetings,

Say network is live on moonbeam alpha testnet and this pull request contains **[Say network oracle service](https://say.network)** details based on the example template. Please let me know if something to change or modify.

Best,
Jeevanjot.

### CODE REVIEW

**Comment by albertov19** [comment]
Hi, some comments,

We are requiring projects to have publicly available GitHub repos. Please share the links to the repos.

https://docs.say.network/moonbeam-testnet/basic-query-with-proofs comment in the require states BNB token and not Glimmer. Please change all token instances to DEV (TestNet token), as the project is deployed on TestNet right now.

Also, I suggest you including what price feeds are available. It is my understand that only `ETH_USD` is available right now.

Happy to revisit this once you've made modifications :)

**Comment by saynetwork** [comment]
Greetings Alberto,

- I have added the Github repo of the oracle bridge.
- Thanks for the heads up on docs, I have changed Glimmer or BNB to `Dev Tokens`
- Users can call any type of price feeds or data (With/Without proof) as long as it is supported by that API providing website. I have provided more examples on it.

Thank you for suggesting those changes. Please, Let me know if anything else to update or modify.

Best,
Jeevanjot.

**Comment by albertov19** [comment]
Hi guys, thank you for doing the modifications.

To be listed in the docs site we expect teams to have fully available open-source code of the implementation. So now I'm not able to approve this PR. Also there is lacking information in regards to the team.

Once you've revisited these issues, feel free to submit another PR.

Regards

**Comment by saynetwork** [comment]
Hello Albertov

As this was a very new project and developing from scratch with open source smart contract codes which I think have more than enough information to help users get started with it.

But as I develop more of it, I will have more code to list.

Thanks.

**Comment by saynetwork** [comment]
Hello Albertov

As this is a very new project and developing from scratch with open source smart contract codes which I think have more than enough information to help users get started with it.

But as I develop more of it, I will have more code to list.

Thanks.

**Pull request closed without merging**
